---
- name: clone git repository to roles directory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: ensure roles directory exists
      file:
        path: "roles"
        state: directory

    - name: clone the git repository into the roles directory
      git:
        repo: 'repo url'
        dest: "roles"
        version: master
        force: yes

    - name: ensure files directory exists
      file:
        path: "files"
        state: directory

    - name: clone the git repository into the files directory
      git:
        repo: 'repo url'
        dest: "files"
        version: master
        forse: yes

    - name: ensure playbooks directory exists
      file:
        path: "playbooks"
        state: directory

    - name: clone the git repository into the playbooks directory
      git:
        repo: 'repo url'
        dest: "playbooks"
        version: master
        forse: yes

